# Site settings
title: Arathy Uday
email: 
description: " "
baseurl: ""
url: "http://ArathyUday.github.io"
github_username:  ArathyUday

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
